### ISSUE TITLE
Improve Zappa integration

### ISSUE THREAD

**Issue by tomchristie** [encode/apistar#123]
See https://github.com/Miserlou/Zappa/issues/801

* Probably want to add `__call__` to App class.
* Autodetection in Zappa.
* Documentation in Zappa.

**Comment by vickumar1981** [comment]
Admittedly, I do not know much about zappa or lambda, but I ran into the following snag following the instructions on the README.

```
> zappa tail

AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
[1495490287800] Traceback (most recent call last):
[1495490287800] File "/var/runtime/awslambda/bootstrap.py", line 226, in handle_event_request
[1495490287800] result = request_handler(json_input, context)
[1495490287800] File "/var/task/handler.py", line 484, in lambda_handler
[1495490287800] return LambdaHandler.lambda_handler(event, context)
[1495490287800] File "/var/task/handler.py", line 240, in lambda_handler
[1495490287800] handler = cls()
[1495490287800] File "/var/task/handler.py", line 129, in __init__
[1495490287801] self.app_module = importlib.import_module(self.settings.APP_MODULE)
[1495490287801] File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
[1495490287801] return _bootstrap._gcd_import(name[level:], package, level)
[1495490287801] File "<frozen importlib._bootstrap>", line 978, in _gcd_import
[1495490287801] File "<frozen importlib._bootstrap>", line 961, in _find_and_load
[1495490287801] File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
[1495490287801] File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
[1495490287801] File "<frozen importlib._bootstrap_external>", line 678, in exec_module
[1495490287801] File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
[1495490287801] File "/var/task/app.py", line 1, in <module>
[1495490287801] from apistar import App, Include, Route
[1495490287801] File "/var/task/apistar/__init__.py", line 8, in <module>
[1495490287801] from apistar.app import App
[1495490287801] File "/var/task/apistar/app.py", line 7, in <module>
[1495490287801] from apistar import commands as cmd
[1495490287801] File "/var/task/apistar/commands/__init__.py", line 4, in <module>
[1495490287801] from apistar.commands.schema import schema
[1495490287801] File "/var/task/apistar/commands/schema.py", line 2, in <module>
[1495490287801] from coreapi.utils import get_installed_codecs
[1495490287801] File "/var/task/coreapi/__init__.py", line 2, in <module>
[1495490287801] from coreapi import auth, codecs, exceptions, transports, utils
[1495490287801] File "/var/task/coreapi/auth.py", line 1, in <module>
[1495490287801] from coreapi.utils import domain_matches
[1495490287801] File "/var/task/coreapi/utils.py", line 5, in <module>
[1495490287802] import pkg_resources
[1495490287802] File "/var/task/pkg_resources.py", line 1519, in <module>
[1495490287802] register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
[1495490287802] AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
[1495490287802] During handling of the above exception, another exception occurred:
[1495490287802] Traceback (most recent call last):
[1495490287802] File "/var/runtime/awslambda/bootstrap.py", line 463, in <module>
[1495490287802] main()
[1495490287802] File "/var/runtime/awslambda/bootstrap.py", line 459, in main
[1495490287802] handle_event_request(request_handler, invokeid, event_body, context_objs, invoked_function_arn)
[1495490287802] File "/var/runtime/awslambda/bootstrap.py", line 240, in handle_event_request
[1495490287803] result = to_json(result)
[1495490287803] File "/var/runtime/awslambda/bootstrap.py", line 215, in to_json
[1495490287803] return json.dumps(obj, default=decimal_serializer)
[1495490287803] File "/var/lang/lib/python3.6/json/__init__.py", line 238, in dumps
[1495490287803] **kw).encode(obj)
[1495490287803] File "/var/lang/lib/python3.6/json/encoder.py", line 199, in encode
[1495490287803] chunks = self.iterencode(o, _one_shot=True)
[1495490287803] File "/var/lang/lib/python3.6/json/encoder.py", line 257, in iterencode
[1495490287803] return _iterencode(o, 0)
[1495490287803] File "/var/runtime/awslambda/bootstrap.py", line 104, in decimal_serializer
[1495490287803] raise TypeError(repr(o) + " is not JSON serializable")
[1495490287803] TypeError: <FrameSummary file /var/task/handler.py, line 484 in lambda_handler> is not JSON serializable
[1495490287904] module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
```

Googling the error, I found this also: https://stackoverflow.com/questions/33365471/importlib-bootstrap-has-no-attribute-sourceloader

**Comment by danbgray** [comment]
I was able to successfully install and run this via lambda.  What version of things are you running?  
could you provide version of zappa, version of python, etc?

**Comment by vickumar1981** [comment]
```
apistar==0.1.17
zappa==0.42.0
```

I'm running on Python 3.5.2.

The `zappa init, deploy,and update` commands work for me.  I get a 503 error when I attempt to hit the root endpoint for the app, which is the `zappa tail` shown above.

**Comment by danbgray** [comment]
I am able to successfully deploy to lambda and hit the endpoint without any errors on python3.6.0 and zappa 0.42.0.  The docs endpoint was missing styling due to static files not being found, so some configuration updates are required to make that part work.

Installing python 3.5.2 and trying again ...

**Comment by vickumar1981** [comment]
thanks @danbgray.  i'm 99.99% sure it's an issue on my end then.  looking at my aws account, it doesn't seem like any `.zip` file is being pushed to the s3 bucket resulting in a 503.  interestingly enough, it also doesn't seem like zappa complains about the fact that the credentials i specified in my `~/.aws/credentials` don't have access to the s3 bucket.  i'll try to get it configured correctly and post the result.

**Comment by audiolion** [comment]
For Zappa Integration, and I guess with just other pieces of this, I feel like we get a few extras with API Star that are not needed. E.g. don't need jinja2, docs/statics, whitenoise, etc. I am wondering if including a `pip install apistar[serverless]` option which only included the barebones needed for serverless deployments would be better.

I know nothing without benchmarking but specifically I am thinking of optimizations for invocation time on AWS Lambda with the size of the function.

**Comment by tomchristie** [comment]
> a few extras with API Star that are not needed. E.g. don't need jinja2, docs/statics, whitenoise, etc

That depends. Many folks will still want the Interactive API docs, however *yes* I absolutely want to provide for a minimal install option, where none of the optional extras are included. I'm not 100% sure what's the best way around to do that yet from a packaging perspective.

**Comment by audiolion** [comment]
As far as docs in Zappa go, I found integrating API Star with it pretty trivial. The existing docs did a great job, really the only thing is to do `wsgi_app = app.wsgi` and passing `wsgi_app` to Zappa's callable, there is no other configuration besides that. I want to see if I can implement this `__call__` though, I am assuming that allows you to just list `app` as Zappa's function and it will call `app.wsgi`

>  Many folks will still want the Interactive API docs

Initially I had the docs included but then I ran into issues with them not rendering on Zappa, I wasn't sure what was happening so I just removed. I also found that I wanted the docs to be at `/` but this is currently impossible with the parse handler, it needs to have at least a letter after the slash or an error occurs. My thought for docs at the root would be when you visit my lambda function you see the documentation for the entire API there.

**Comment by vickumar1981** [comment]
@audiolion   the `__call__` functionality of the app was implemented here: https://github.com/tomchristie/apistar/commit/671b6e4c8d28618fe44fbe11c3ae7a8c3afb9a98

you ** shouldn't ** need to wrap the `wsgi_app` part anymore.

**Comment by tomchristie** [comment]
@audiolion @vickumar1981 If someone could confirm it's working as expected and then make a PR to update the README that'd be ace.

**Comment by vickumar1981** [comment]
@tomchristie  i'm going to check if it works as expected this weekend.

**Comment by audiolion** [comment]
Oh wow, I guess putting links to issues in commits isn't always the greatest idea, sorry for the spam but the PR is open

**Comment by tomchristie** [comment]
Worth noting that we now have a regular ol' WSGI app, with __call__ on the App instance itself, rather than on a `.wsgi` property. Adding autodetection to Zappa, and include API Star in the Zappa docs is something that someone oughta be able to do ahead and tackle without any further blockers.

**Comment by tomchristie** [comment]
Closing this off given that 0.6 is moving to a framework-agnostic suite of API tools, and will no longer include the server. See https://discuss.apistar.org/t/api-star-as-a-framework-independant-tool/614 and #624.
