### ISSUE TITLE
ModuleNotFoundError: No module named 'django' when using SQLAlchemy

### ISSUE THREAD

**Issue by jriggins** [encode/apistar#187]
Looks like when trying to use SQLAlchemy (and not Django ORM) in master, we get a failure:

```bash
$ apistar run
Traceback (most recent call last):
  File "/Users/jriggins/src/optimumsymmetry/survey-system-2/python/venv/bin/apistar", line 11, in <module>
    load_entry_point('apistar==0.1.17', 'console_scripts', 'apistar')()
  File "/Users/jriggins/src/optimumsymmetry/survey-system-2/python/venv/lib/python3.6/site-packages/apistar/cli.py", line 44, in main
    app = get_current_app()
  File "/Users/jriggins/src/optimumsymmetry/survey-system-2/python/venv/lib/python3.6/site-packages/apistar/cli.py", line 27, in get_current_app
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/jriggins/src/optimumsymmetry/survey-system-2/python/app.py", line 5, in <module>
    from apistar.backends.sqlalchemy_backend import SQLAlchemy
  File "/Users/jriggins/src/optimumsymmetry/survey-system-2/python/venv/lib/python3.6/site-packages/apistar/backends/__init__.py", line 1, in <module>
    from apistar.backends.django_backend import DjangoBackend
  File "/Users/jriggins/src/optimumsymmetry/survey-system-2/python/venv/lib/python3.6/site-packages/apistar/backends/django_backend.py", line 1, in <module>
    from django import setup
ModuleNotFoundError: No module named 'django'
```

**Comment by tomchristie** [comment]
We won't get this import error anymore, since 0.2 no longer attempts to import both at the higher level `__init__.py`
