### ISSUE TITLE
ValueError: dictionary update sequence element #0 has length 1; 2 is required

### ISSUE THREAD

**Issue by jet10000** [encode/apistar#202]
```
Traceback (most recent call last):
  File "/Users/xy/env-apistar/src/apistar/apistar/app.py", line 99, in func
    core.run_pipeline(app.router.exception_pipeline, state)
  File "/Users/xy/env-apistar/src/apistar/apistar/core.py", line 62, in run_pipeline
    state[output] = function(**kwargs)
  File "/Users/xy/env-apistar/src/apistar/apistar/app.py", line 96, in func
    state[output] = function(**kwargs)
  File "/Users/xy/env-apistar/src/apistar/apistar/http.py", line 140, in build
    value = validate(cls.schema, value, key=arg_name)
  File "/Users/xy/env-apistar/src/apistar/apistar/schema.py", line 20, in validate
    return schema(value)
  File "/Users/xy/env-apistar/src/apistar/apistar/schema.py", line 224, in __init__
    value = dict(value)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

views.py
```

def create_star(models: DjangoBackend, star: schemas.Star):
    Star = models.Star
    star = Star(**star)
    star.save()
    return {'star': {'name': star.name, 'id': star.id}}
```

schemas.py

```
from apistar import schema


class Star(schema.Object):

    properties = {
        'name': schema.String(max_length=255)
    }
```

modes.py
```
from django.db import models


class Star(models.Model):

    name = models.CharField(max_length=255)

```

routers.py
```

routes = [
    ...
    Route('/api/stars/', 'POST', create_star)
]
```

**Comment by maziarz** [comment]
Running into the same problem here. It seems like missing exception handling as far as i have guessed. If you in fact supply the routing with the correct data it should pass without errors.

**Comment by tomchristie** [comment]
Given that all of those bits have now been redesigned I'm going to close this one off.
