### ISSUE TITLE
Default example not working

### ISSUE THREAD

**Issue by kianxineki** [encode/apistar#266]
```
apistar new .
./app.py
./tests.py
```
```
apistar run
 * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 170-045-591
127.0.0.1 - - [30/Aug/2017 19:12:00] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/apistar/frameworks/wsgi.py", line 115, in __call__
    response = self.http_injector.run(self.exception_handler, state=state)
  File "/usr/local/lib/python3.5/dist-packages/apistar/components/dependency.py", line 110, in run
    ret = step.func(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/apistar/frameworks/wsgi.py", line 112, in __call__
    response = self.http_injector.run(handler, state=state)
  File "/usr/local/lib/python3.5/dist-packages/apistar/components/dependency.py", line 110, in run
    ret = step.func(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/apistar/components/dependency.py", line 386, in empty
    return query_params.get(name)
AttributeError: 'QueryParams' object has no attribute 'get'
```
run tests
```
apistar test 
============================================ test session starts =============================================
platform linux -- Python 3.5.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /tmp/prueb/asdasd, inifile:
collected 2 items                                                                                             

tests.py .F

================================================== FAILURES ==================================================
_____________________________________________ test_http_request ______________________________________________

    def test_http_request():
        """
        Testing a view, using the test client.
        """
        client = TestClient(app)
>       response = client.get('http://localhost/')

tests.py:18: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3/dist-packages/requests/sessions.py:480: in get
    return self.request('GET', url, **kwargs)
/usr/local/lib/python3.5/dist-packages/apistar/test.py:249: in request
    return super().request(method, url, **kwargs)
/usr/lib/python3/dist-packages/requests/sessions.py:468: in request
    resp = self.send(prep, **send_kwargs)
/usr/lib/python3/dist-packages/requests/sessions.py:576: in send
    r = adapter.send(request, **kwargs)
/usr/local/lib/python3.5/dist-packages/apistar/test.py:113: in send
    wsgi_response = self.app(environ, start_response)
/usr/local/lib/python3.5/dist-packages/apistar/frameworks/wsgi.py:115: in __call__
    response = self.http_injector.run(self.exception_handler, state=state)
/usr/local/lib/python3.5/dist-packages/apistar/components/dependency.py:110: in run
    ret = step.func(**kwargs)
/usr/local/lib/python3.5/dist-packages/apistar/frameworks/wsgi.py:112: in __call__
    response = self.http_injector.run(handler, state=state)
/usr/local/lib/python3.5/dist-packages/apistar/components/dependency.py:110: in run
    ret = step.func(**kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <apistar.components.dependency.HTTPResolver object at 0x7ffb20512780>, name = 'name', kwargs = {}
query_params = QueryParams([])

    def empty(self,
              name: ParamName,
              kwargs: KeywordArgs,
              query_params: http.QueryParams) -> str:
        """
            Handles unannotated parameters for HTTP requests.
            These types use either a matched URL keyword argument, or else
            a query parameter.
    
            Args:
                name: The name of the parameter.
                kwargs: The URL keyword arguments, as returned by the router.
                query_params: The query parameters of the incoming HTTP request.
    
            Returns:
                The value that should be used for the handler function.
            """
        if name in kwargs:
            return kwargs[name]
>       return query_params.get(name)
E       AttributeError: 'QueryParams' object has no attribute 'get'

/usr/local/lib/python3.5/dist-packages/apistar/components/dependency.py:386: AttributeError
```

app.py
```python
from apistar import Include, Route
from apistar.frameworks.wsgi import WSGIApp as App
from apistar.handlers import docs_urls, static_urls


def welcome(name=None):
    if name is None:
        return {'message': 'Welcome to API Star!'}
    return {'message': 'Welcome to API Star, %s!' % name}


routes = [
    Route('/', 'GET', welcome),
    Include('/docs', docs_urls),
    Include('/static', static_urls)
]

app = App(routes=routes)


if __name__ == '__main__':
    app.main()
```

**Comment by kianxineki** [comment]
In python 3.6.2 works fine, python 3.5.2 does not work

**Comment by JoeJasinski** [comment]
Same Issue, I think. 

Steps to reproduce:

```
    # On  ubuntu 16.04
    python3 -mvenv envs/apistar
    . ./envs/apistar/bin/activate
    pip install apistar==0.2.10
    apistar new .
    apistar run
    # browse to http://localhost:8080
```

Error Generated

```
Traceback (most recent call last):
  File "/home/jjasinski/test/apistar/envs/apistar/lib/python3.5/site-packages/apistar/frameworks/wsgi.py", line 115, in __call__
    response = self.http_injector.run(self.exception_handler, state=state)
  File "/home/jjasinski/test/apistar/envs/apistar/lib/python3.5/site-packages/apistar/components/dependency.py", line 110, in run
    ret = step.func(**kwargs)
  File "/home/jjasinski/test/apistar/envs/apistar/lib/python3.5/site-packages/apistar/frameworks/wsgi.py", line 112, in __call__
    response = self.http_injector.run(handler, state=state)
  File "/home/jjasinski/test/apistar/envs/apistar/lib/python3.5/site-packages/apistar/components/dependency.py", line 110, in run
    ret = step.func(**kwargs)
  File "/home/jjasinski/test/apistar/envs/apistar/lib/python3.5/site-packages/apistar/components/dependency.py", line 386, in empty
    return query_params.get(name)
AttributeError: 'QueryParams' object has no attribute 'get'
```

Packages installed

```
(apistar):~/test/apistar$ pip freeze
apistar==0.2.10
certifi==2017.7.27.1
chardet==3.0.4
coreapi==2.3.1
coreschema==0.0.4
idna==2.6
itypes==1.1.0
Jinja2==2.9.6
MarkupSafe==1.0
pkg-resources==0.0.0
py==1.4.34
pytest==3.2.1
requests==2.18.4
uritemplate==3.0.0
urllib3==1.22
Werkzeug==0.12.2
whitenoise==3.3.0
```

Python Version

```
(apistar):~/test/apistar$ python
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
```

**Comment by tomchristie** [comment]
Okay, I suspect this is an issue in 3.5.2 that may not be present in 3.5.3+ (So far have confirmed QueryParams *does* include a .get method in 3.6 at least.)

**Comment by m1yag1** [comment]
I'm using Python 3.6.0a3 and am currently having this issue.

**Comment by frol** [comment]
@m1yag1 Could you upgrade to a stable Python release (3.6.3)? Is there a reason why you stuck with Alpha release of Python?

**Comment by catroot** [comment]
Whats wrong with 3.5.2?
```
from apistar.http import QueryParams
a=QueryParams({"Type":"new"})
a.get("Type")
```
ends with 

>  Traceback (most recent call last):
>   File "test_apistar.py", line 4, in <module>
>     a.get("Type")
> AttributeError: 'QueryParams' object has no attribute 'get'
>

**Comment by tomchristie** [comment]
Closing, given #400.
