### ISSUE TITLE
apistart.typesystem.Object cannot serialize  sqlalchemy mapped object after session committed

### ISSUE THREAD

**Issue by living42** [encode/apistar#284]
As a example below will crash

```python
...
class Job(typesystem.Object):
    properties = {
        ...
    }

def create_job(session: Session) -> Job:
   job = models.Job(...)
   session.add(job)
   session.commit()
   return Job(job)
```

Sounds like

```
Traceback (most recent call last):
  File "/Users/living/Code/tracels/apistar/playground/.pyvenv/lib/python3.6/site-packages/gevent/pywsgi.py", line 935, in handle_one_response
    self.run_application()
  File "/Users/living/Code/tracels/apistar/playground/.pyvenv/lib/python3.6/site-packages/gevent/pywsgi.py", line 908, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/Users/living/Code/tracels/apistar/playground/.pyvenv/lib/python3.6/site-packages/apistar/frameworks/wsgi.py", line 121, in __call__
    response = self.http_injector.run_all(funcs, state=state)
  File "/Users/living/Code/tracels/apistar/playground/.pyvenv/lib/python3.6/site-packages/apistar/components/dependency.py", line 132, in run_all
    ret = step.func(**kwargs)
  File "/Users/living/Code/tracels/apistar/playground/.pyvenv/lib/python3.6/site-packages/apistar/frameworks/wsgi.py", line 117, in __call__
    response = self.http_injector.run_all(funcs, state=state)
  File "/Users/living/Code/tracels/apistar/playground/.pyvenv/lib/python3.6/site-packages/apistar/components/dependency.py", line 132, in run_all
    ret = step.func(**kwargs)
  File "/Users/living/Code/tracels/apistar/playground/api.py", line 119, in create_job
    return serialization.Job(job)
  File "/Users/living/Code/tracels/apistar/playground/.pyvenv/lib/python3.6/site-packages/apistar/typesystem.py", line 190, in __init__
    raise TypeSystemError(errors)
apistar.exceptions.TypeSystemError: {'id': 'This field is required.',  'message': 'This field is required.', 'status': 'This field is required.', 'created_at': 'This field is required.', 'finished_at': 'This field is required.'}
```

With some researching, i notice `apistar.typesystem.Object` using `__dict__` attribute to get attributes of an object. That's a problem.

By default sqlalchemy's will expire an object, after `session.commit`, then `__dict__`  to be cleared.

```
>>> job = models.Job(...)
>>> session.add(job)
>>> session.commit()
>>> job.__dict__
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x107992a58>}
```

sqlalchemy will refresh object automatically when you access that object via `obj.xxx` syntax, but not `obj.__dict__['xxx']`

**Comment by tomchristie** [comment]
> With some researching, i notice apistar.typesystem.Object using __dict__ attribute to get attributes of an object. That's a problem.

We don't do that with the new typesystem coming in with #400, so I'm going to close this off. The new release should be with us fairly soon.
