### ISSUE TITLE
Authentication and permission with HTMLRenderer()

### ISSUE THREAD

**Issue by 7robertodantas** [encode/apistar#346]
I am facing a problem using authentication/permission and a route function annotated with HTMLRenderer(). The problem occurs when the user doesn't have the permission or is not allowed to access the route. In this situation, is produced automatically a response data that should be rendered as json:

```json
{
    "message": "Forbidden"
}
```

But if the function has HTMLRenderer, even if it also has JSONRenderer, the apistar tries to use only the HTMLRenderer, and since the parameter data in this case is a dict (not str nor bytes) it results in AssertationError:
```python
@annotate(renderers=[JSONRenderer(), HTMLRenderer()])
```

https://github.com/encode/apistar/blob/7d7dc3a11983915882687ca8607b9eca2ae5ff57/apistar/renderers.py#L37-L38

```bash
127.0.0.1 - - [28/Oct/2017 12:57:49] "GET /oauth/authorize HTTP/1.1" 500 -
Traceback (most recent call last):
  File "project/authorization-server/.env/lib/python3.6/site-packages/apistar/frameworks/wsgi.py", line 134, in __call__
    response = self.http_injector.run_all(funcs, state=state)
  File "project/authorization-server/.env/lib/python3.6/site-packages/apistar/components/dependency.py", line 141, in run_all
    ret = step.func(**kwargs)
  File "project/authorization-server/.env/lib/python3.6/site-packages/apistar/hooks.py", line 68, in render_response
    content = injector.run(renderer.render, {'response_data': data})
  File "project/authorization-server/.env/lib/python3.6/site-packages/apistar/components/dependency.py", line 336, in run
    ret = step.func(**kwargs)
  File "project/authorization-server/.env/lib/python3.6/site-packages/apistar/renderers.py", line 38, in render
    assert isinstance(data, (str, bytes))
AssertionError

```

**Comment by tomchristie** [comment]
Closing this off given that 0.6 is moving to a framework-agnostic suite of API tools, and will no longer include the server. See https://discuss.apistar.org/t/api-star-as-a-framework-independant-tool/614 and #624.
