### ISSUE TITLE
can use starred expression only as assignment target

### ISSUE THREAD

**Issue by dangyibo1992** [encode/apistar#389]
```
# apistar 
Traceback (most recent call last):
  File "/bin/apistar", line 9, in <module>
    load_entry_point('apistar==0.3.9', 'console_scripts', 'apistar')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 568, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/apistar-0.3.9-py3.4.egg/apistar/__init__.py", line 14, in <module>
    from apistar.frameworks.cli import CliApp
  File "/usr/lib/python3.4/site-packages/apistar-0.3.9-py3.4.egg/apistar/frameworks/cli.py", line 37
    commands = [*self.BUILTIN_COMMANDS, *commands]
                       ^
SyntaxError: can use starred expression only as assignment target
```
why? help.

**Comment by pslacerda** [comment]
You need Python 3.5 at least.

**Comment by brunoliveira8** [comment]
With Python 3.5, I got the following error:

`Traceback (most recent call last):
  File "/home/bruno/Projects/apistar101/lib/python3.5/site-packages/apistar/frameworks/wsgi.py", line 134, in __call__
    response = self.http_injector.run_all(funcs, state=state)
  File "/home/bruno/Projects/apistar101/lib/python3.5/site-packages/apistar/components/dependency.py", line 141, in run_all
    ret = step.func(**kwargs)
  File "/home/bruno/Projects/apistar101/lib/python3.5/site-packages/apistar/frameworks/wsgi.py", line 130, in __call__
    response = self.http_injector.run_all(funcs, state=state)
  File "/home/bruno/Projects/apistar101/lib/python3.5/site-packages/apistar/components/dependency.py", line 141, in run_all
    ret = step.func(**kwargs)
  File "/home/bruno/Projects/apistar101/lib/python3.5/site-packages/apistar/components/dependency.py", line 629, in empty
    return query_params.get(name)
`

I believe Python 3.6 is needed at least. There is a PR (https://github.com/encode/apistar/pull/364) to support Python 3.5 but it is not merged yet

**Comment by dangyibo1992** [comment]
i get,so much tks !
