### ISSUE TITLE
TypeError: 'coroutine' object is not iterable

### ISSUE THREAD

**Issue by zopyx** [encode/apistar#401]
The generated asyncio app skeleton raises the following error:

```
(app.backend) ajung@dev ~/src/app.backend (master) $ bin/gunicorn app:app --bind 0.0.0.0
[2018-03-14 13:37:41 +0100] [18183] [INFO] Starting gunicorn 19.7.1
[2018-03-14 13:37:41 +0100] [18183] [INFO] Listening at: http://0.0.0.0:8000 (18183)
[2018-03-14 13:37:41 +0100] [18183] [INFO] Using worker: sync
[2018-03-14 13:37:41 +0100] [18186] [INFO] Booting worker with pid: 18186
[2018-03-14 13:37:45 +0100] [18186] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/home/ajung/src/app.backend/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ajung/src/app.backend/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 181, in handle_request
    for item in respiter:
TypeError: 'coroutine' object is not iterable
[2018-03-14 13:37:46 +0100] [18186] [ERROR] Error handling request /favicon.ico
Traceback (most recent call last):
  File "/home/ajung/src/app.backend/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ajung/src/app.backend/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 181, in handle_request
    for item in respiter:
TypeError: 'coroutine' object is not iterable
[2018-03-14 13:37:47 +0100] [18186] [ERROR] Error handling request /docs
Traceback (most recent call last):
  File "/home/ajung/src/app.backend/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ajung/src/app.backend/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 181, in handle_request
    for item in respiter:
TypeError: 'coroutine' object is not iterable
[2018-03-14 13:37:48 +0100] [18186] [ERROR] Error handling request /favicon.ico
Traceback (most recent call last):
  File "/home/ajung/src/app.backend/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ajung/src/app.backend/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 181, in handle_request
    for item in respiter:
TypeError: 'coroutine' object is not iterable
```

**Comment by tomchristie** [comment]
Looks like you’re trying to use ‘gunicorn’ to run an async App. Use ‘uvicorn’ instead for that, or use ‘WSGIApp’
