### ISSUE TITLE
Async components can't be proloaded

### ISSUE THREAD

**Issue by sirex** [encode/apistar#413]
Currently async components can't be preloaded, because during preload uvloop is not yet available.

For example:

```python
from apistar import Component
from apistar import Route
from apistar.frameworks.asyncio import ASyncIOApp as App

import aiopg


class Database:

    def __init__(self, pool):
        self.pool = pool

    async def version(self):
        async with self.pool.acquire() as conn:
            async with conn.cursor() as cur:
                await cur.execute('SELECT version()')
                return await cur.fetchone()


async def init_database():
    return Database(await aiopg.create_pool('dbname=postgres'))


async def version(db: Database):
    return await db.version()


components = [
    Component(Database, init=init_database),
]

routes = [
    Route('/', 'GET', version),
]

app = App(components=components, routes=routes)
app.main()
```

This will give following error:

```
Traceback (most recent call last):
  File "apistar/frameworks/asyncio.py", line 125, in __call__
    response = await self.http_injector.run_all_async(funcs, state=state)
  File "apistar/components/dependency.py", line 430, in run_all_async
    ret = step.func(**kwargs)
  File "apistar/frameworks/asyncio.py", line 121, in __call__
    response = await self.http_injector.run_all_async(funcs, state=state)
  File "apistar/components/dependency.py", line 428, in run_all_async
    ret = await step.func(**kwargs)
  File "/tmp/error.py", line 25, in version
    return await db.version()
AttributeError: 'coroutine' object has no attribute 'version'
```

APIStar version: 0.3.9.

**Comment by tomchristie** [comment]
First place to start this: Do `sanic` or `aiohttp` provide initialization hooks for async components?

What would it look like if we had one? Add an (optionally async) `initialize` method to components, or something else?

**Comment by jcugat** [comment]
Aiohttp has the signals `on_startup` and `on_cleanup` for this:

```python
from aiopg.sa import create_engine

async def create_aiopg(app):
    app['pg_engine'] = await create_engine(
        user='postgre',
        database='postgre',
        host='localhost',
        port=5432,
        password=''
    )

async def dispose_aiopg(app):
    app['pg_engine'].close()
    await app['pg_engine'].wait_closed()

app.on_startup.append(create_aiopg)
app.on_cleanup.append(dispose_aiopg)
```

https://docs.aiohttp.org/en/stable/web_advanced.html#aiohttp-web-signals

**Comment by sirex** [comment]
Sanic has `(before|after)_server_(start|stop)`:

```python
bp = Blueprint('my_blueprint')

@bp.listener('before_server_start')
async def setup_connection(app, loop):
    global database
    database = mysql.connect(host='127.0.0.1'...)

@bp.listener('after_server_stop')
async def close_connection(app, loop):
    await database.close()
```

http://sanic.readthedocs.io/en/latest/sanic/blueprints.html#start-and-stop

**Comment by sirex** [comment]
Regarding how this could look, I would see it like this:

```python
import aiopg

from apistar import App, Route
from apistar.events import on_start
from apistar.server.components import Component


class Database:

    def __init__(self):
        on_start(self.connect)

    async def connect(self):
        self.pool = await aiopg.create_pool('dbname=postgres')


class DatabaseComponent(Component):

    def resolve(self) -> Database:
        return Database()


async def version(db: Database):
    async with db.pool.acquire() as conn:
        async with conn.cursor() as cur:
            await cur.execute('SELECT version()')
            return {
                'version': await cur.fetchone(),
            }


routes = [
    Route('/version/', method='GET', handler=version)
]

components = [DatabaseComponent()]

app = App(routes=routes)
```

I really like API Star's dependency injections, but event hooks are quite limited. So instead there could be a proper event handling system, where it would be possible to inject some actions into specific app initializaction or request handling parts. Like in this case, creating database connection on app startup, when components are initialized and event loop is available.

This would allow to add more events and framework users or library developers would be able to create custom events.

**Comment by cliffxuan** [comment]
@tomchristie can you please explain why `preload` not a provided feature anymore? we used this feature before and it makes sense to us.

**Comment by akalipetis** [comment]
I believe that having optional `initialize`/`cleanup` methods, possibly async, is more than enough.

We had the same issue with [`aioredis`](https://github.com/aio-libs/aioredis), which we circumvented in a not so nice way.

I believe that the initialization/cleanup logic should be inside the component and not as separate hooks, so that components can be easily be provided as libraries, without extra logic in the code importing them.

Thus, I propose something like:

```python
class RedisPoolComponent(Component):

    async def initialize(self):
        self.pool = await aioredis.create_pool('redis://localhost', minsize=5, maxsize=10)

    async def cleanup(self):
        await self.pool.close()

    def resolve(self) -> aioredis.Redis:
        return self.pool
```

**Comment by ZhouBox** [comment]
I want to ask if this feature has been added.
