### ISSUE TITLE
apistar cant work and the commandline cant recognized from 0.4.1 above

### ISSUE THREAD

**Issue by youngorchen** [encode/apistar#445]
and for 0.4.0, when enter apistar it will have the error like :

Traceback (most recent call last):
  File "c:\users\williamchen\anaconda3\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\williamchen\anaconda3\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\williamchen\Envs\mxonline\Scripts\apistar.exe\__main__.py", line 5, in <module>
ImportError: cannot import name 'main'

**Comment by youngorchen** [comment]
and the same happen in the centos 7, apistar cant be found ...

**Comment by tomchristie** [comment]
As per [the release notes](http://www.encode.io/apistar/topics/release-notes/)...

> The apistar command line tool has not yet been re-introduced.

Run API Star applications directly instead, as-per the example in the quickstart.
