### ISSUE TITLE
coreapi-cli fails retrieving the schema

### ISSUE THREAD

**Issue by jgirardet** [encode/apistar#447]
I can't retrive schema with coreapi client.

minimal example + error below

``` python
from apistar import App

app = App(
    routes=[],
    schema_url="/schema/")
if __name__ == '__main__':
    # app.serve(ho starun_wsgi(app)
    options = {
        'use_debugger': True,
        'use_reloader': True,
    }
    app.serve('127.0.0.1', 5000, **options)


"""

jim:$  coreapi get http://localhost:5000/schema/
 
Traceback (most recent call last):
  File "/home/jim/.local/bin/coreapi", line 11, in <module>
    load_entry_point('coreapi-cli==1.0.9', 'console_scripts', 'coreapi')()
  File "/home/jim/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/jim/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/jim/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jim/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jim/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jim/.local/lib/python3.6/site-packages/coreapi_cli/main.py", line 147, in get
    doc = client.get(url, force_codec=force_codec)
  File "/home/jim/.local/lib/python3.6/site-packages/coreapi/client.py", line 136, in get
    return transport.transition(link, decoders, force_codec=force_codec)
  File "/home/jim/.local/lib/python3.6/site-packages/coreapi/transports/http.py", line 380, in transition
    result = _decode_result(response, decoders, force_codec)
  File "/home/jim/.local/lib/python3.6/site-packages/coreapi/transports/http.py", line 294, in _decode_result
    result = codec.load(response.content, **options)
  File "/home/jim/.local/lib/python3.6/site-packages/coreapi/codecs/base.py", line 24, in load
    return self.decode(*args, **kwargs)
  File "/home/jim/.local/lib/python3.6/site-packages/coreapi/codecs/download.py", line 143, in decode
    os.rename(temp_path, output_path)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpf4u4sowp.download' -> '/home/jim/.coreapi/downloads/schema'
"""
```

**Comment by rhelms** [comment]
That looks like like a coreapi issue rather than an apistar issue, and may be particular to any environment where the temporary path is on a different file system to the output path.

https://stackoverflow.com/a/43967659/343614

**Comment by tomchristie** [comment]
Closed the equivalent issue in the (currently undocumented) APIStar client library... #450.
Not sure we'll address the issue in coreapi since we're in the process of moving away from it.
