### ISSUE TITLE
KeyError: 'return_value' on handlers that annotate `http.Response` on return

### ISSUE THREAD

**Issue by Bogdanp** [encode/apistar#465]
I ran into this while upgrading my app to 0.5.

Minimal example:

```python
from apistar import App, Route, http


def index() -> http.Response:
    return http.Response(b"hello", headers={
        "content-type": "foo"
    })


app = App(routes=[Route("/", "GET", index)])
app.serve(host="127.0.0.1", port=8000, debug=True)
```

Visiting `/` will raise a KeyError:

```
Traceback (most recent call last):
  File "/Users/bogdan/.virtualenvs/blockfraud/lib/python3.6/site-packages/apistar/server/app.py", line 202, in __call__
    return self.injector.run(funcs, state)
  File "/Users/bogdan/.virtualenvs/blockfraud/lib/python3.6/site-packages/apistar/server/injector.py", line 104, in run
    state[output_name] = func(**func_kwargs)
  File "/Users/bogdan/.virtualenvs/blockfraud/lib/python3.6/site-packages/apistar/server/app.py", line 160, in finalize_wsgi
    raise exc_info[0].with_traceback(exc_info[1], exc_info[2])
  File "/Users/bogdan/.virtualenvs/blockfraud/lib/python3.6/site-packages/apistar/server/app.py", line 198, in __call__
    return self.injector.run(funcs, state)
  File "/Users/bogdan/.virtualenvs/blockfraud/lib/python3.6/site-packages/apistar/server/injector.py", line 104, in run
    state[output_name] = func(**func_kwargs)
  File "/Users/bogdan/.virtualenvs/blockfraud/lib/python3.6/site-packages/apistar/server/app.py", line 193, in __call__
    return self.injector.run(funcs, state)
  File "/Users/bogdan/.virtualenvs/blockfraud/lib/python3.6/site-packages/apistar/server/injector.py", line 102, in run
    func_kwargs = {key: state[val] for key, val in kwargs.items()}
  File "/Users/bogdan/.virtualenvs/blockfraud/lib/python3.6/site-packages/apistar/server/injector.py", line 102, in <dictcomp>
    func_kwargs = {key: state[val] for key, val in kwargs.items()}
KeyError: 'return_value'
```

It works fine if you drop the `-> http.Response` annotation.

**Comment by tomchristie** [comment]
Thanks. Having a look into that now.

**Comment by Bogdanp** [comment]
Thanks!
