### ISSUE TITLE
Array validation does not work

### ISSUE THREAD

**Issue by marekkosta** [encode/apistar#496]
Regard the following:
```python
from apistar import App, Route
from apistar import types, validators


class Numbers(types.Type):
    numbers = validators.Array(validators.Integer)


def test(nums: Numbers)-> dict:
    res = [x+1 for x in nums['numbers']]
    return {'numbers': res}


routes = [
    Route('/test', method='POST', handler=test),
]

app = App(routes=routes)


if __name__ == '__main__':
    app.serve('127.0.0.1', 8000, debug=True)
```
then I go:
```bash
curl -X POST -H 'Content-Type: application/json' -i http://localhost:8000/test --data '{ "numbers": [1,2,3] }'
```
This crashes with the following Traceback:
```bash
Traceback (most recent call last):
  File "/home/mkosta/.local/share/virtualenvs/apistar-test-b1c5t0T_/lib/python3.6/site-packages/apistar/server/app.py", line 222, in __call__
    return self.injector.run(funcs, state)
  File "/home/mkosta/.local/share/virtualenvs/apistar-test-b1c5t0T_/lib/python3.6/site-packages/apistar/server/injector.py", line 106, in run
    state[output_name] = func(**func_kwargs)
  File "/home/mkosta/.local/share/virtualenvs/apistar-test-b1c5t0T_/lib/python3.6/site-packages/apistar/server/app.py", line 166, in finalize_wsgi
    raise exc_info[0].with_traceback(exc_info[1], exc_info[2])
  File "/home/mkosta/.local/share/virtualenvs/apistar-test-b1c5t0T_/lib/python3.6/site-packages/apistar/server/app.py", line 215, in __call__
    return self.injector.run(funcs, state)
  File "/home/mkosta/.local/share/virtualenvs/apistar-test-b1c5t0T_/lib/python3.6/site-packages/apistar/server/injector.py", line 106, in run
    state[output_name] = func(**func_kwargs)
  File "/home/mkosta/.local/share/virtualenvs/apistar-test-b1c5t0T_/lib/python3.6/site-packages/apistar/server/app.py", line 206, in __call__
    return self.injector.run(funcs, state)
  File "/home/mkosta/.local/share/virtualenvs/apistar-test-b1c5t0T_/lib/python3.6/site-packages/apistar/server/injector.py", line 106, in run
    state[output_name] = func(**func_kwargs)
  File "/home/mkosta/.local/share/virtualenvs/apistar-test-b1c5t0T_/lib/python3.6/site-packages/apistar/server/validation.py", line 101, in resolve
    return validator.validate(data, allow_coerce=True)
  File "/home/mkosta/.local/share/virtualenvs/apistar-test-b1c5t0T_/lib/python3.6/site-packages/apistar/validators.py", line 383, in validate
    allow_coerce=allow_coerce
  File "/home/mkosta/.local/share/virtualenvs/apistar-test-b1c5t0T_/lib/python3.6/site-packages/apistar/validators.py", line 512, in validate
    allow_coerce=allow_coerce
TypeError: validate() missing 1 required positional argument: 'value'
```

**Comment by GomZik** [comment]
You should instantiate `validators.Integer`, so, if your example will looks like 

```
class Numbers(types.Type):
    numbers = validators.Array(validators.Integer())
```

It should works fine

**Comment by tomchristie** [comment]
Thanks @GomZik! (Tho we should be type checking that argument)
