### ISSUE TITLE
Docs/Guide give error: AttributeError: type object 'list' has no attribute '__args__'

### ISSUE THREAD

**Issue by atmosuwiryo** [encode/apistar#523]
[This](https://docs.apistar.com/api-guide/routing/) routing guide, give me error:

> (apistar) ➜  test python app.py   
Traceback (most recent call last):
  File "app.py", line 39, in <module>
    Route('/users/', method='GET', handler=list_users),
  File "/Users/atmosuwiryo/.virtualenvs/apistar/lib/python3.6/site-packages/apistar/server/core.py", line 17, in __init__
    self.link = self.generate_link(url, method, handler, self.name)
  File "/Users/atmosuwiryo/.virtualenvs/apistar/lib/python3.6/site-packages/apistar/server/core.py", line 21, in generate_link
    response = self.generate_response(handler)
  File "/Users/atmosuwiryo/.virtualenvs/apistar/lib/python3.6/site-packages/apistar/server/core.py", line 83, in generate_response
    annotation = self.coerce_generics(annotation)
  File "/Users/atmosuwiryo/.virtualenvs/apistar/lib/python3.6/site-packages/apistar/server/core.py", line 94, in coerce_generics
    annotation.__args__ and
AttributeError: type object 'list' has no attribute '__args__'

This is the 'list_users' function, same as the guide:

> def list_users(app: App) -> list:
    return [
        {
            'username': username,
            'url': app.reverse_url('get_user', user_id=user_id)
        } for user_id, username in USERS.items()
    ]

This is my env:

> (apistar) ➜  test python --version
Python 3.6.4
(apistar) ➜  test pip freeze
apistar==0.5.12
certifi==2018.4.16
chardet==3.0.4
idna==2.6
Jinja2==2.10
MarkupSafe==1.0
requests==2.18.4
urllib3==1.22
Werkzeug==0.14.1
whitenoise==3.3.1

Additional info:
if I change this code:

> def list_users(app: App) -> list:

to:

> def list_users(app: App) -> dict:

Then there is no error anymore.

**Comment by zhang20054460** [comment]
line 94:  use "getattr(annotation, '__args__', None) and" instead of "annotation.__args__ and"
