### ISSUE TITLE
AttributeError: 'StaticFile' object has no attribute 'file_not_modified'

### ISSUE THREAD

**Issue by songww** [encode/apistar#563]
```python
127.0.0.1:55262 - - [23/May/2018:17:08:49] "GET /static/apistar/js/jquery.json-view.min.js" 500 14
Traceback (most recent call last):
  File ".venv/lib/python3.6/site-packages/apistar/server/app.py", line 334, in asgi_callable
    await self.injector.run_async(funcs, state)
  File ".venv/lib/python3.6/site-packages/apistar/server/injector.py", line 132, in run_async
    state[output_name] = func(**func_kwargs)
  File ".venv/lib/python3.6/site-packages/apistar/server/app.py", line 325, in asgi_callable
    await self.injector.run_async(funcs, state)
  File ".venv/lib/python3.6/site-packages/apistar/server/injector.py", line 130, in run_async
    state[output_name] = await func(**func_kwargs)
  File ".venv/lib/python3.6/site-packages/apistar/server/handlers.py", line 28, in serve_static_asgi
    await instance(receive, send)
  File ".venv/lib/python3.6/site-packages/apistar/server/staticfiles.py", line 80, in __call__
    status, headers, file = await self.get_response(self.scope['method'], self.headers)
  File ".venv/lib/python3.6/site-packages/apistar/server/staticfiles.py", line 116, in get_response
    elif self.static_file.file_not_modified(request_headers):
AttributeError: 'StaticFile' object has no attribute 'file_not_modified'
```

**Comment by songww** [comment]
`self.whitenoise.files.get()` got a `whitenoise.responders.StaticFile` object.
That has `is_not_modified` attribute, not `file_not_modified`: https://github.com/evansd/whitenoise/blob/master/whitenoise/responders.py#L169

**Comment by songww** [comment]
https://github.com/evansd/whitenoise/pull/181
