### ISSUE TITLE
Exception handling semantics seem broken in apistar 0.5.25

### ISSUE THREAD

**Issue by bryanapperson** [encode/apistar#565]
Given the functions:

```
def create_config(session: Session, config: app_data_types.ConfigType) \
        -> app_data_types.ConfigType:
    """Save the config to the DB."""
    logger.debug('Creating configuration in database.')
    try:
            config_model = db_models.ConfigModel(**config)
            session.add(config_model)
    except BaseException:
        logger.warning("Hit intergrity error")
        raise exceptions.HTTPException(status_code=409)
    return config

def upload_config(session: Session,
                  config: app_data_types.ConfigType) -> http.JSONResponse:
    """Upload a config."""
    logger.info('Uploadingconfiguration.')
    return http.JSONResponse(create_config(session, config), 201)
```

I am trying to catch a SQLAlchemy exception on calling `upload_config` repeatedly with the same unique key, and gracefully return a `409` response code. I at first tried using a more fine grained exception (`IntegrityError`). The exception was not being caught. So I tried catching any exception and the exception is still not caught.

The above will trigger the `on_error` event hook and never hit the except clause.

My event hook:

```
class SQLATransaction:
    """Transaction event hook class.

    Handles commit or rollback on failed transactions.
    """
    def on_response(self, response: http.Response, session: Session,
                    exc: Exception) -> http.Response:
        """Commit or rollback transaction based on response."""
        if exc is None:
            session.commit()
            logger.debug('Commit transaction')
            self.remove_session()
        else:
            session.rollback()
            logger.debug('Exception, rollback transaction')
            self.remove_session()
        return response

    def on_error(self, response: http.Response,
                 session: Session) -> http.Response:
        """Roll back the session on error."""
        session.rollback()
        logger.debug('Error, rollback transaction')
        self.remove_session()
        return response

    @staticmethod
    def remove_session():
        """Remove the session."""
        db_orm.Session.remove()
```

See the console output:

```
2018-05-23 11:06:57,728 INFO     (<memory at 0x104b4b1c8>)
2018-05-23 11:06:57,729 INFO sqlalchemy.engine.base.Engine ROLLBACK
2018-05-23 11:06:57,729 INFO     ROLLBACK
2018-05-23 11:06:57,731 DEBUG    Error, rollback transaction
[2018-05-23 11:06:57 -0400] [40138] [ERROR] Error handling request /inventory/v1/config/
Traceback (most recent call last):
  File "/Users/me/.local/share/virtualenvs/OQsQTSup/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/me/.local/share/virtualenvs/OQsQTSup/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed:
```

This seems broken. There is no documented way to handle expected exceptions that works. Even if I don't raise any exception it still hits the `on_error` hook. Please advise if I am missing something here.

**Comment by bryanapperson** [comment]
Looks like the exception was being thrown in the event_hook on commit.
