### ISSUE TITLE
Maximum Recursion Depth Exceeded in Comparison Error: Nested Array of types.Type

### ISSUE THREAD

**Issue by aleksarias** [encode/apistar#573]
I have created and successfully used two types for posting and returning JSON. I have a customer type and a transaction type. Both of these are flat. 
I saw the docs said we could combine types to form more complex ones. Is there currently support for a nested array of a type? I'm trying to get a JSON response that contains the customer information along with all of the customer's transactions. 

The types:
```
class TransactionType(types.Type):
    account_owner = validators.String(max_length=150)
    amount = validators.Number()
    category = validators.String(max_length=150)
    category_id = validators.String(max_length=25)
    date = validators.Date()
    city = validators.String(max_length=100)
    latitude = validators.Number()
    longitude = validators.Number()
    state = validators.String(max_length=15)
    store_number = validators.String(max_length=30)
    zip = validators.String(max_length=5)

class CustomerDataType(types.Type):
    customer_id = validators.String()
    banking_data_source = validators.String()
    data_access_id = validators.String()
    primary_bank_routing = validators.String()
    primary_bank_account = validators.String()
    created_at = validators.DateTime()
    updated_at = validators.DateTime()
    bank_decision_status = validators.String()
    transactions = validators.Array(items=TransactionType)
```
The view:
```
def get_customer(session: Session, customer_id: str) -> http.JSONResponse:
    """
    Returns customer information for a customer

    :param customer_id:
    :param session:
    :return:
    """
    customer: CustomerModel = session.query(CustomerModel).filter_by(customer_id=customer_id).first()
    return http.JSONResponse(
        CustomerDataType(customer),
        status_code=200
    )
```
The models:
```
class CustomerModel(Base):
    __tablename__ = 'customers'
    customer_id = Column(String(100, collation='utf8_bin'), primary_key=True, nullable=False)
    banking_data_source = Column(String(100), nullable=False)
    data_access_id = Column(String(100), nullable=False)
    primary_bank_routing = Column(String(10), nullable=False)
    primary_bank_account = Column(String(20), nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow, nullable=False)
    bank_decision_status = Column(String(25), nullable=True)
    accounts = relationship("AccountModel", cascade="save-update, merge, delete")
    balances = relationship("BalanceModel", cascade="save-update, merge, delete")
    transactions = relationship("TransactionModel", cascade="save-update, merge, delete")

class TransactionModel(Base):
    __tablename__ = 'transactions'
    customer_id = Column(String(100, collation='utf8_bin'), ForeignKey(CustomerModel.customer_id))
    account_id = Column(String(100, collation='utf8_bin'), ForeignKey(AccountModel.account_id))
    account_owner = Column(String(150))
    amount = Column(Float)
    category = Column(String(150))
    category_id = Column(String(25))
    date = Column(Date)
    address = Column(String(150))
    city = Column(String(100))
    latitude = Column(Float)
    longitude = Column(Float)
    state = Column(String(15))
    store_number = Column(String(30))
    zip = Column(String(5))
```
The error:
```
127.0.0.1 - - [29/May/2018 14:18:02] "GET /customer/test_user_2 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/alex/PycharmProjects/bankserv/rest_api/.venv/lib/python3.6/site-packages/apistar/server/app.py", line 243, in __call__
    return self.injector.run(funcs, state)
  File "/home/alex/PycharmProjects/bankserv/rest_api/.venv/lib/python3.6/site-packages/apistar/server/injector.py", line 106, in run
    state[output_name] = func(**func_kwargs)
  File "/home/alex/PycharmProjects/bankserv/rest_api/.venv/lib/python3.6/site-packages/apistar/server/app.py", line 187, in finalize_wsgi
    raise exc_info[0].with_traceback(exc_info[1], exc_info[2])
  File "/home/alex/PycharmProjects/bankserv/rest_api/.venv/lib/python3.6/site-packages/apistar/server/app.py", line 236, in __call__
    return self.injector.run(funcs, state)
  File "/home/alex/PycharmProjects/bankserv/rest_api/.venv/lib/python3.6/site-packages/apistar/server/injector.py", line 106, in run
    state[output_name] = func(**func_kwargs)
  File "/home/alex/PycharmProjects/bankserv/rest_api/.venv/lib/python3.6/site-packages/apistar/server/app.py", line 227, in __call__
    return self.injector.run(funcs, state)
  File "/home/alex/PycharmProjects/bankserv/rest_api/.venv/lib/python3.6/site-packages/apistar/server/injector.py", line 106, in run
    state[output_name] = func(**func_kwargs)
  File "/home/alex/PycharmProjects/bankserv/rest_api/source/views.py", line 35, in get_customer
    status_code=200
  File "/home/alex/PycharmProjects/bankserv/rest_api/.venv/lib/python3.6/site-packages/apistar/http.py", line 192, in __init__
    self.content = self.render(content)
  File "/home/alex/PycharmProjects/bankserv/rest_api/.venv/lib/python3.6/site-packages/apistar/http.py", line 239, in render
    return json.dumps(content, **options).encode('utf-8')
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/alex/PycharmProjects/bankserv/rest_api/.venv/lib/python3.6/site-packages/apistar/http.py", line 242, in default
    if isinstance(obj, types.Type):
  File "/usr/lib/python3.6/abc.py", line 190, in __instancecheck__
    subclass in cls._abc_negative_cache):
  File "/usr/lib/python3.6/_weakrefset.py", line 75, in __contains__
    return wr in self.data
RecursionError: maximum recursion depth exceeded in comparison


```

**Comment by aleksarias** [comment]
Seems like this may be related to: https://github.com/cwacek/python-jsonschema-objects/issues/28

**Comment by tomchristie** [comment]
Redundant given that we now use https://github.com/encode/typesystem
